function Activate(keys, a, b, c)
    print("testscript activate")
    print(keys)
    print(a)
    print(b)
    print(c)
end

function OnPostSpawn(a, b,c)
    print("OnPostSpawn")
    print(a)
    print(b)
    print(c)
end

function Test(a, b, c, d, e)
    local ent = Entities:FindByName(nil, "testsc")
    print(CScriptKeyValues)
    PrintTable(getmetatable(CScriptKeyValues))
    DeepPrintTable(getmetatable(CScriptKeyValues))
    DeepPrintTable(CScriptKeyValues)
--    print(CScriptKeyValues.GetValue(thisEntity, "kala"))
--    print(CScriptKeyValues:GetValue("kala"))
--    print(CScriptKeyValues.GetValue("kala"))
    if true then
        return nil
    end
    print(ent.EntityGroup)
    print(ent:GetIntAttr("kala"))
    print(ent:GetIntAttr("vscripts"))
    print(ent:GetIntAttr("targetname"))
    print(self)
    print(thisEntity:GetIntAttr("kala"))
    print(ent.__KeyValueFromString)
    print(ent.__KeyValueFromInt)
    print(ent.GetValue)
    print(ent.GetValues)
    print(ent.GetStrAttr)
    print(ent.GetIntAttr)
    print(a)
    print(a.EntityGroup)
    print(a.caller.EntityGroup)
    print(b)
    print(c)
    print(d)
    PrintTable(a)
    PrintTable(a.activator)
--    print(self)
--    print(thisEntity)
--    PrintTable(thisEntity)
--    PrintTable(getmetatable(thisEntity))
    --    DeepPrintTable(a.caller)
    --    DeepPrintTable(getmetatable(a.caller))
    print(a.caller:GetContext("vscripts"))
    print(a.caller:GetContext("targetname"))
    print(a.caller:GetContext("Group00"))
    print(a.caller:GetClassname())
    print(a.caller.FDesc)
    print(a.caller.__KeyValueFromString)
    print(a.caller.__KeyValueFromInt)
    local test = {}
    a.caller:GatherCriteria(test)
    print(test)
    print(#test)
--    PrintTable(test)
--    DeepPrintTable(a.caller.FDesc)
--    PrintTable(self)

--    PrintTable(getmetatable(a))
--    PrintTable(getmetatable(a.activator))
--    PrintTable(getmetatable(a.caller))
end


return hoi